#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generator: schreibt verification-results.json, findings/*.md, raw/*.txt
für den swiss-democracy-mcp Audit-Run. Reproduzierbar — keine Inline-Heredocs.
Datenbasis: manuelle Code-Review + automatisierte greps (siehe raw/)."""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
SERVER = "src/swiss_democracy_mcp/server.py"

# (id, category, severity, status, [evidence], [gaps],
#  observed, expected, remediation, effort)
CHECKS = [
 ("ARCH-001","ARCH","medium","pass",
  ["10 Tools, alle snake_case mit Präfix `democracy_*` (server.py:341-1071)",
   "Keine Spaces/Punkte/Sonderzeichen; konsistente Convention im ganzen Repo",
   "Ausführliche Docstrings mit Args/Returns pro Tool"],
  [], "", "", "", ""),
 ("ARCH-002","ARCH","medium","partial",
  ["Tool-Descriptions sind ausführlich (>100 Zeichen Median), mit Args/Returns",
   "Differenzierung ähnlicher Tools (search vs detail vs cantonal) klar"],
  ["Keine strukturierten `<use_case>`/`<important_notes>`/`<example>`-Tags (0 Treffer in src/)"],
  "Beschreibungen sind prosaisch und ausführlich, enthalten aber keine maschinell trennscharfen Use-Case-Tags.",
  "≥80% der Tools mit `<use_case>`-Tag plus Caveats in `<important_notes>`.",
  "Pro Tool die Description um `<use_case>`/`<important_notes>`-Tags ergänzen (siehe ARCH-002 Pass-Pattern).",
  "S — pro Tool 5–10 Min."),
 ("ARCH-003","ARCH","medium","partial",
  ["`democracy_search_votes` liefert strukturiertes Envelope mit total/count/has_more auch bei 0 Treffern (server.py:452-459)"],
  ["Kein `match_type`-Feld, kein Fuzzy-/Suggestion-Mechanismus",
   "Detail-/Party-/Cantonal-Tools geben bei Nicht-Treffer nur `{\"error\": \"...nicht gefunden\"}` zurück (server.py:512,597,665)"],
  "Leere Resultate werden ohne Heuristik/Vorschläge zurückgegeben; Lookup-Tools liefern blosse Fehlermeldung.",
  "Bei nicht-sensiblen Such-Tools: Fuzzy-Fallback + `match_type` + actionable Hinweis.",
  "Bei `search_votes` Fuzzy-/Vorschlags-Logik ergänzen, `match_type` (exact/fuzzy/none) ins Envelope. Daten sind public → Heuristik unbedenklich.",
  "S — ~30 Min pro Such-Tool."),
 ("ARCH-004","ARCH","high","partial",
  ["Tool-Handler greifen nicht auf Transport-Internals (`request.`/headers) zu — voll transport-agnostisch",
   "Dual-Transport via `MCP_TRANSPORT` stdio|streamable_http unterstützt (server.py:1118-1125)"],
  ["Konfiguration über Modul-globale Vars + `os.environ`, kein Pydantic-Settings-Objekt",
   "Kein Lifespan/Dependency-Injection; `httpx.AsyncClient` wird pro Call erzeugt (siehe SDK-001)"],
  "IoC teilweise erfüllt: Handler sind transport-agnostisch und Dual-Transport ist gegeben, aber Konfiguration/Setup ist nicht über ein Settings-/Lifespan-Objekt zentralisiert.",
  "Settings-Objekt (pydantic-settings) + gemeinsamer Lifespan für alle Transports.",
  "`Settings(BaseSettings)` einführen, geteilten `@asynccontextmanager`-Lifespan registrieren (Synergie SDK-001).",
  "M — 1–3 Tage."),
 ("ARCH-005","ARCH","critical","partial",
  ["Keine Hardcoded Secrets im Code (grep clean)",
   "SRGSSR-Credentials werden aus `os.environ.get` geladen, ohne Real-Key-Defaults (server.py:145-146)",
   "Keine Secrets in Logs (kein Logging vorhanden)"],
  ["Keine `.gitignore` im Repo → `.env` nicht ausgeschlossen",
   "Keine `.env.example` mit Platzhaltern",
   "Kein CI-Secret-Scan (gitleaks/trufflehog) in den Workflows",
   "Credentials als `str`, nicht `SecretStr`"],
  "Kern erfüllt (keine Hardcoded Secrets), aber die Defense-in-Depth-Hygiene fehlt vollständig.",
  "Env-Vars als Minimum + .gitignore/.env.example + CI-Secret-Scan + SecretStr-Repräsentation.",
  "1) `.gitignore` mit `.env`,`.env.*` (ausser `.env.example`). 2) `.env.example` committen. 3) gitleaks-Action in CI. 4) Credentials als `SecretStr`.",
  "S — < 1 Tag."),
 ("ARCH-006","ARCH","high","pass",
  ["10 Tools (≤12-Heuristik erfüllt)",
   "Use-Case-orientiert, kein 1:1-CRUD-API-Mapping",
   "Anchor-Demo-Query mit 2–3 Tool-Calls beantwortbar (README Demo)"],
  [], "", "", "", ""),
 ("ARCH-007","ARCH","medium","pass",
  ["Tools liefern gedanklich abgeschlossene Resultate (vote_detail komplett, cantonal alle 26 Kantone)",
   "`search_votes` liefert vollständige Summaries (nicht nur IDs) → erste Antwort ohne Folge-Call möglich"],
  ["Natürliche Drill-down-Verkettung search→detail vorhanden (akzeptabel, da search selbst aussagekräftig)"],
  "", "", "", ""),
 ("ARCH-008","ARCH","medium","fail",
  ["Nur `@mcp.tool` verwendet — keine `@mcp.resource`, keine `@mcp.prompt` (0 Treffer)"],
  ["Keine Begründung im README für Tools-only-Ansatz",
   "Read-only-Lookups (vote_detail, cantonal) sind Resource-Kandidaten"],
  "Server nutzt ausschliesslich das Tools-Primitiv, ohne Resources/Prompts und ohne dokumentierte Begründung.",
  "Mind. zwei Primitive ODER dokumentierte Begründung im README.",
  "README-Sektion «MCP-Primitive» mit Begründung (Phase-1-Wrapper) ergänzen; optional read-only Lookups als Resources (`vote://{anr}`) prüfen.",
  "S — Begründung < 1 Tag; M bei Resource-Migration."),
 ("ARCH-009","ARCH","high","pass",
  ["ALLE 10 Tools haben explizite Annotations: readOnlyHint/destructiveHint/idempotentHint/openWorldHint (server.py:342-348 u.a.)",
   "readOnlyHint=True konsistent mit Read-only-Verhalten",
   "openWorldHint=True für alle externen Datenquellen"],
  ["Keine Annotations-Übersicht im README (minor)"],
  "", "", "", ""),
 ("ARCH-011","ARCH","medium","partial",
  ["README.md, README.de.md, LICENSE, pyproject.toml vorhanden",
   "src/-Layout korrekt, tests/, .github/workflows/ (ci.yml + publish.yml) vorhanden"],
  ["`CHANGELOG.md` fehlt"],
  "Repo-Struktur weitgehend standardkonform, aber CHANGELOG.md fehlt.",
  "Alle Top-Level-Pflicht-Files inkl. CHANGELOG.md.",
  "`CHANGELOG.md` im Keep-a-Changelog-Format anlegen.",
  "S — < 1 Tag."),
 ("ARCH-012","ARCH","medium","fail",
  ["FastMCP-Default-Protocol genutzt"],
  ["`protocolVersion` nicht explizit gepinnt",
   "Kein CHANGELOG.md",
   "Keine README-Sektion «MCP Protocol Version»",
   "Kein Dependabot/Renovate (.github/dependabot.yml fehlt)"],
  "Keine Spec-Versionierungs-Disziplin: kein Pinning, kein CHANGELOG, keine automatisierten SDK-Updates.",
  "protocolVersion gepinnt + CHANGELOG + README-Protocol-Sektion + Dependabot.",
  "1) Protocol-Version im README dokumentieren. 2) CHANGELOG anlegen. 3) `.github/dependabot.yml` für pip.",
  "S — < 1 Tag."),
 ("CH-004","CH","medium","partial",
  ["README dokumentiert alle Quellen mit Lizenzen (Data Sources, Safety&Limits, License-Sektion: Swissvotes CC BY 4.0 etc.)"],
  ["Tool-Antworten enthalten kein `source`/`license`-Feld (0 Treffer im Code)",
   "Keine Per-Record-Provenance im Response-Envelope"],
  "Lizenz-Attribution ist im README vorbildlich, fehlt aber in den maschinenlesbaren Tool-Antworten.",
  "Tool-Antworten mit `source`+`license`-Feld; Provenance pro Datensatz.",
  "Response-Envelope um `source`/`license`/`attribution` ergänzen (CC BY 4.0: Autor, Quelle, Lizenz).",
  "S — < 1 Tag."),
 ("OBS-001","OBS","high","partial",
  ["Tool-Handler fangen Exceptions ab und crashen nicht (`_handle_error`, server.py:236-249)",
   "Test deckt Not-Found-Pfad ab (test_get_vote_detail_not_found)"],
  ["Fehler werden als normaler String/JSON zurückgegeben, NICHT als `isError`-Tool-Result markiert",
   "Keine standardisierten Protocol-Error-Codes; kein Test für Protocol-Error-Pfad"],
  "Anwendungsfehler werden gefangen, aber als erfolgreicher Tool-Output mit «Fehler:»-Text geliefert statt mit isError-Flag.",
  "Execution-Errors mit `isError: true`; Protocol-Errors mit Standard-Codes.",
  "Fehler über das FastMCP-Error-Signaling (Exception → isError) statt String-Return; Protocol-Error-Test ergänzen.",
  "M — 1–3 Tage."),
 ("OBS-002","OBS","high","partial",
  ["`_handle_error` liefert benutzerfreundliche, gemaskte Meldungen (keine Stacktraces)",
   "Kein `traceback.format_exc()` im Code"],
  ["`mask_error_details=True` im FastMCP-Konstruktor nicht gesetzt (server.py:275)",
   "Generischer Fallback `f\"Fehler: {type(e).__name__}: {e}\"` (server.py:249) kann Internals exponieren"],
  "Fehlerdetails werden grösstenteils maskiert, aber FastMCP-seitig nicht hart erzwungen und der Catch-all-Zweig leakt Exception-Repr.",
  "`mask_error_details=True` + ausschliesslich user-friendly Messages.",
  "`FastMCP(..., mask_error_details=True)`; generischen Fallback durch generische Meldung ersetzen, Original nur ins (stderr-)Log.",
  "S — < 1 Tag."),
 ("OBS-003","OBS","medium","fail",
  ["Kein Logging-Code vorhanden"],
  ["Kein Structured Logger (structlog/loguru) in dependencies",
   "Keine Severity-Stufen, kein bound context pro Tool-Call"],
  "Der Server hat überhaupt kein Logging — weder strukturiert noch unstrukturiert.",
  "Structured Logger (structlog) mit JSON/logfmt, ≥4 Severity-Stufen, bound context.",
  "structlog einführen, Logger auf stderr (siehe OBS-004), pro Tool-Call tool/correlation-id binden.",
  "S — < 1 Tag."),
 ("OBS-004","OBS","critical","pass",
  ["KEINE `print()`-Statements in src/ (grep clean)",
   "Kein Logging auf stdout → stdout bleibt für JSON-RPC-Protocol reserviert",
   "Dual-Transport ohne transport-abhängigen Logging-Switch"],
  ["Logging insgesamt fehlt (als OBS-003 erfasst, nicht hier blockierend)"],
  "", "", "", ""),
 ("OPS-001","OPS","high","partial",
  ["respx-HTTP-Mocking in Unit-Tests (tests/test_server.py:12,155ff)",
   "Live-Tests mit `@pytest.mark.live` markiert, Marker in pyproject registriert",
   "CI läuft `pytest -m \"not live\"` (ci.yml)"],
  ["BFS- und Polis-Tools haben keine Unit-Tests (nur Swissvotes getestet)",
   "Nur ~11 Unit-Tests / 2 Live-Tests — unter dem Richtwert ≥5 Unit + ≥1 Live pro Tool",
   "Separater nightly Live-Test-Workflow fehlt"],
  "Test-Infrastruktur ist solide (respx, live-Marker, CI), aber die Abdeckung der BFS-/Polis-Tools fehlt.",
  "≥5 Unit + ≥1 Live-Test pro Tool, separater Live-Workflow.",
  "Unit-Tests für `bfs_*`- und `polis_*`-Tools (respx-Mocks) ergänzen; nightly Live-Workflow hinzufügen.",
  "M — 1–3 Tage."),
 ("OPS-002","OPS","medium","partial",
  ["README mit Demo, Installation, Tools, Architektur (ASCII-Diagramm), Safety&Limits, Known Limitations, License",
   "README.de.md parallel mit gleichen Top-Level-Sektionen",
   "CONTRIBUTING.md vorhanden"],
  ["`CHANGELOG.md` fehlt",
   "Keine dedizierte Configuration-Sektion (Env-Vars nur in Installation gestreut)"],
  "Dokumentation ist umfangreich und bilingual, aber CHANGELOG fehlt und Konfiguration ist nicht gebündelt.",
  "Alle 8 Pflicht-Sektionen inkl. CHANGELOG + Configuration.",
  "CHANGELOG anlegen; «Configuration»-Sektion (MCP_TRANSPORT/HOST/PORT, SRGSSR_*) ergänzen.",
  "S–M."),
 ("OPS-003","OPS","high","partial",
  ["Phasen explizit im README deklariert (Phase 1/2/3 in Tools-Sektion)",
   "Phasen konsistent mit Annotations (alle read-only = Phase 1)"],
  ["Kein Roadmap-File",
   "Phasenübergangs-Voraussetzungen (Audit/ISDS/DSG) nicht dokumentiert",
   "Kein CHANGELOG für Phasenübergänge"],
  "Phasenmodell ist im README angelegt und konsistent, aber Roadmap und Übergangskriterien fehlen.",
  "Explizite Phase + Roadmap-File + dokumentierte Übergangskriterien.",
  "`docs/roadmap.md` mit Phasen-Tasks und Übergangskriterien; aktuelle Phase prominent deklarieren.",
  "S."),
 ("SCALE-002","SCALE","high","partial",
  ["Tools sind zustandslos (kein Mcp-Session-Id-abhängiger State); In-Memory-CSV-Cache ist reiner Cache",
   "stdio-first; HTTP-Transport sekundär"],
  ["Keine Sticky-Sessions / kein Shared-State-Session-Manager (Redis o.ä.)",
   "Kein Failover-/Multi-Instance-Konzept dokumentiert"],
  "HTTP-Transport wird ausgeliefert, aber ohne Session-/LB-Strategie. Praktisches Risiko gering, da Tools zustandslos sind.",
  "Sticky-Sessions oder Shared-State + definierte TTL für horizontales Scaling.",
  "Single-Instance-Annahme im README dokumentieren; bei Cloud-Scaling Sticky-Sessions auf `Mcp-Session-Id` (Ingress) konfigurieren.",
  "M — 1–3 Tage (nur bei Scaling)."),
 ("SDK-001","SDK","high","fail",
  ["Kein `lifespan`/`@asynccontextmanager`/`AsyncExitStack` (0 Treffer)",
   "`httpx.AsyncClient(...)` wird in jedem Helper pro Tool-Call neu erzeugt (server.py:115,165,196,212)"],
  ["Kein geteilter Client/Connection-Pool über Lifespan"],
  "Pro Tool-Call wird ein neuer HTTP-Client samt Connection-Pool aufgebaut — explizites Anti-Pattern des Katalogs.",
  "Lifespan mit `@asynccontextmanager`, geteilter `httpx.AsyncClient`, Cleanup im finally.",
  "`@asynccontextmanager`-Lifespan einführen, `httpx.AsyncClient` einmalig erzeugen und via Context/State injizieren; `FastMCP(..., lifespan=...)`.",
  "S — < 1 Tag."),
 ("SDK-002","SDK","medium","partial",
  ["Pydantic ≥2 für alle Input-Modelle; Field-Defaults via `Field(default=...)`"],
  ["Tool-Returns sind `-> str` (json.dumps), keine BaseModel/TypedDict-Return-Typen",
   "Kein konsistenter Envelope mit `source`/`provenance`",
   "Keine `Literal`-Typen für enumerable Felder (level, lang)"],
  "Inputs sind stark typisiert, aber Tool-Returns sind unstrukturierte JSON-Strings ohne typisierten Envelope.",
  "Typisierte Returns (BaseModel/TypedDict) mit source/provenance/results/count; Literal-Types.",
  "Return-Modelle definieren; `level`/`lang` als `Literal[...]`; Envelope mit source/count vereinheitlichen (Synergie CH-004/SDK-002).",
  "S — < 1 Tag."),
 ("SDK-003","SDK","medium","partial",
  ["Tools sind grösstenteils schnell (Swissvotes-CSV gecacht 24h)"],
  ["Kein `ctx: Context`-Parameter in irgendeinem Tool",
   "Kein `ctx.report_progress()` bei potenziell langsamen Calls (CSV-Initial-Download mehrere MB)",
   "Fehler werden nicht via `ctx.warning/error` gemeldet"],
  "Keine Context-Injektion; langlaufende Operationen (initialer CSV-Download) ohne Progress/Logging.",
  "`ctx: Context` für Tools >2s; `ctx.report_progress()`; `ctx.warning/error` statt stummem Schlucken.",
  "`ctx: Context`-Parameter ergänzen, beim CSV-Initial-Load `ctx.report_progress()` senden.",
  "S — < 1 Tag."),
 ("SDK-004","SDK","high","partial",
  ["HTTP-Transport (streamable_http) wird unterstützt"],
  ["Keine CORS-Middleware konfiguriert (kein `expose_headers`/`allow_headers`)",
   "`Mcp-Session-Id` nicht explizit für Browser-Clients exponiert"],
  "Im HTTP-Modus ist keine CORS-Konfiguration vorhanden; Browser-basierte Clients erhalten `Mcp-Session-Id` nicht.",
  "CORS mit `expose_headers`/`allow_headers` inkl. `Mcp-Session-Id`, explizite Origins in Prod.",
  "CORS-Middleware für HTTP-Transport konfigurieren; `allow_origins` als explizite Liste (kein `*`).",
  "S — < 1 Tag."),
 ("SEC-004","SEC","critical","fail",
  ["`democracy_bfs_get_vote_results(result_url)` reicht einen beliebigen User/LLM-URL direkt an `_bfs_get` → `httpx.get(url)` weiter (server.py:837-853,210-215)",
   "`result_url` hat nur min/max_length (10/500), KEINE Scheme-/Host-Validierung (server.py:809-817)",
   "Kein HTTPS-Enforcement, keine IP-Blocklist, kein Egress-Proxy"],
  ["Cloud-Metadata-IP 169.254.169.254 nicht blockiert",
   "Private/Loopback-Ranges nicht blockiert"],
  "Das BFS-Result-Tool fetcht eine frei wählbare URL ohne jegliche Validierung — klassische SSRF. Ein manipuliertes Tool-Argument (z.B. `http://169.254.169.254/...`) zwingt den Server, interne/Cloud-Metadata-Endpunkte abzurufen.",
  "HTTPS-Enforcement + Resolved-IP gegen Blocklist (privat/link-local/loopback) + DNS-Pinning; Cloud-Metadata explizit blockiert.",
  "1) `result_url` gegen Allow-List der bekannten BFS-Hosts (opendata.swiss/bfs.admin.ch) prüfen statt freier URL. 2) HTTPS erzwingen. 3) Resolved-IP-Blocklist + DNS-Pinning (siehe SEC-004 Pass-Pattern). 4) Idealerweise: nur Resource-ID statt voller URL als Tool-Arg akzeptieren.",
  "M — 1–3 Tage."),
 ("SEC-005","SEC","high","fail",
  ["Kein `getaddrinfo`/DNS-Pinning im Code; httpx-Default mit impliziter Doppel-Auflösung",
   "Folgt direkt aus fehlender SSRF-Prevention (SEC-004)"],
  ["Kein gepinnter IP-Request, kein Host-Header-Erhalt für TLS-SNI"],
  "Da keinerlei SSRF-Schutz existiert, fehlt auch die DNS-Rebinding-Mitigation (TOCTOU) vollständig.",
  "Einmalige DNS-Resolution + gepinnte IP für den Request + Original-Host für TLS-SNI.",
  "Custom `PinnedTransport` (SEC-005 Pass-Pattern) oder Egress-Proxy (Smokescreen). Voraussetzung: SEC-004 zuerst.",
  "M — 1–3 Tage."),
 ("SEC-006","SEC","high","pass",
  ["Default-Transport ohne ENV-Var ist `stdio` (server.py:1119)",
   "HTTP/SSE nur via expliziter `MCP_TRANSPORT=streamable_http`",
   "README dokumentiert stdio/Claude Desktop primär + Cloud separat"],
  [], "", "", "", ""),
 ("SEC-007","SEC","high","partial",
  ["Server ist als PyPI-Paket via uvx/pip lauffähig"],
  ["Kein Dockerfile / keine Container-Hardening (USER non-root, readOnlyRootFilesystem, cap drop)",
   "Kein seccomp/SecurityContext"],
  "Es existiert keinerlei Sandboxing-Artefakt. Für einen lokalen stdio-Server ist das Defense-in-Depth, fehlt hier aber komplett — relevant sobald der dokumentierte Cloud-/Render-Pfad genutzt wird.",
  "Gehärtetes Dockerfile (non-root, read-only FS, cap drop) für den Container-/Cloud-Pfad.",
  "Multi-Stage-Dockerfile mit `USER 10001`, read-only FS + tmpfs; bei K8s SecurityContext setzen.",
  "S — < 1 Tag."),
 ("SEC-008","SEC","medium","pass",
  ["Keine pre/postinstall-Hooks; hatchling-Build, sauberes pyproject",
   "README zeigt vollen Installations-Befehl (uvx + claude_desktop_config)",
   "publish.yml nutzt PyPI Trusted Publisher (`id-token: write`, `environment: pypi`, pypa/gh-action-pypi-publish) → Sigstore-Signatur",
   "CONTRIBUTING.md erklärt Build-Prozess"],
  [], "", "", "", ""),
 ("SEC-009","SEC","critical","partial",
  ["Keine eigene Session-Verwaltung im Code; Tools sind zustandslos",
   "`auth_model=none` → keine User-Identität, keine privilegierten Operationen pro Session"],
  ["Keine kryptografische Session-Generierung/Binding im Code (verlässt sich auf FastMCP-Defaults)",
   "Kein explizites TTL / keine serverseitige Invalidierung"],
  "Es gibt keine eigene Session-Bindung. Da der Server unauthentifiziert und zustandslos ist (keine user-spezifischen Daten/Privilegien), ist der Hijacking-Impact gering — der Check ist hier formal anwendbar (dual transport), aber praktisch von niedriger Kriminalität.",
  "Kryptografische Session-IDs an validierte user_id gebunden — relevant erst mit Auth/State.",
  "FastMCP-Session-ID-Generierung verifizieren/dokumentieren; bei zukünftiger Auth/State Binding gemäss SEC-009 implementieren.",
  "M — nur bei Einführung von Auth/State."),
 ("SEC-013","SEC","high","partial",
  ["SRGSSR-Credentials werden aus Env-Vars geladen (Stufe 1), keine Hardcoded Keys",
   "Datenklasse Public Open Data → Stufe 1 grundsätzlich akzeptabel"],
  ["Kein Secret-Manager (Stufe 3) und keine dokumentierte Begründung für Stufe 1",
   "Credentials als `str` statt `SecretStr`"],
  "Plain-Env-Var-Storage ist für Public-Open-Data vertretbar, aber weder dokumentiert noch via SecretStr abgesichert.",
  "Stufe-1-Begründung dokumentieren ODER Secret-Manager (Stufe 3); SecretStr-Repräsentation.",
  "`docs/secret-management.md` mit Stufe-1-Begründung; Credentials als `SecretStr`.",
  "S — < 1 Tag."),
 ("SEC-016","SEC","critical","fail",
  ["HTTP-Modus bindet per Default an `0.0.0.0`: `os.environ.get(\"MCP_HOST\", \"0.0.0.0\")` (server.py:1121)"],
  ["Default sollte `127.0.0.1` sein; 0.0.0.0 nur explizit im Container",
   "README erklärt die lokal/container-Differenzierung beim Binding nicht",
   "Keine Warnung beim Start auf 0.0.0.0"],
  "Im HTTP-Modus lauscht der Server defaultmässig auf allen Interfaces (0.0.0.0) — NeighborJack-Risiko: jeder im selben Netz erreicht den Port.",
  "Default-Host `127.0.0.1`; `0.0.0.0` nur explizit (z.B. im Dockerfile).",
  "Default auf `127.0.0.1` ändern; `MCP_HOST=0.0.0.0` nur im Dockerfile setzen; README-Hinweis + optionale Start-Warnung.",
  "S — < 1 Tag."),
 ("SEC-018","SEC","high","pass",
  ["Alle Tool-Args über Pydantic-Modelle mit `extra=\"forbid\"` (server.py:293ff)",
   "Numerische Constraints `ge/le` (year 1848–2100, limit 1–100), String `max_length`",
   "Cross-Field-Validator (year_to ≥ year_from, server.py:331-337)"],
  ["`strict=True` nicht gesetzt (durch extra=forbid + Constraints weitgehend kompensiert)",
   "`result_url` ohne Host-Pattern (im SSRF-Finding SEC-004 adressiert)"],
  "", "", "", ""),
 ("SEC-019","SEC","critical","partial",
  ["Nur 2 der 3 Trifecta-Fähigkeiten: liest (öffentliche) Daten + externe Requests; KEIN Write/Send",
   "Alle Tools read-only (GET)"],
  ["Trifecta-Bewertung nicht im README/docs dokumentiert",
   "SSRF (SEC-004) schafft de-facto einen Forge-/Exfil-Kanal — verschärft die Bewertung bis SEC-004 gefixt ist"],
  "Der Server hält ≤2 Trifecta-Fähigkeiten (gut), dokumentiert die Bewertung aber nicht. Die offene SSRF-Lücke (SEC-004) untergräbt die «kein Exfil»-Annahme bis zur Behebung.",
  "Dokumentierte Trifecta-Bewertung; max. zwei Fähigkeiten.",
  "Kurze Trifecta-/ADR-Notiz in `docs/`; SEC-004 schliessen, damit der Exfil-Kanal verschwindet.",
  "S — < 1 Tag (Bewertung)."),
 ("SEC-020","SEC","critical","pass",
  ["Keine `os.system`/`subprocess`/`shell=True`/`eval`/`exec`/`os.popen` (grep clean)",
   "Reiner Library-First-Code (httpx, csv, json)"],
  [], "", "", "", ""),
 ("SEC-021","SEC","high","fail",
  ["Externe Requests an feste Hosts (swissvotes.ch, opendata.swiss, api.srgssr.ch) — aber nicht erzwungen",
   "`result_url` (BFS) erlaubt beliebige Hosts (server.py:853)"],
  ["Keine Code-Layer-Allow-List (`frozenset` erlaubter Hosts) / kein `assert_host_allowed`",
   "Keine Network-Layer-Egress-Kontrolle dokumentiert",
   "Kein `docs/network-egress.md`"],
  "Es gibt keine Egress-Allow-List — weder im Code noch im Netzwerk. Zusammen mit dem freien `result_url` (SEC-004) ist ausgehender Traffic unbeschränkt.",
  "Code-Layer-`frozenset`-Allow-List + Pre-Request-Check + Network-Layer-Egress-Policy + Doku.",
  "`ALLOWED_HOSTS = frozenset({...})` + `assert_host_allowed(url)` vor jedem Request; `docs/network-egress.md`.",
  "M — 1–3 Tage."),
]

CATEGORY = {"ARCH":"ARCH","SEC":"SEC","CH":"CH","OBS":"OBS","OPS":"OPS","SCALE":"SCALE","SDK":"SDK"}

def slug(title_id): return title_id.lower()

def main():
    raw_meta = json.loads((OUT/"audit-meta.json").read_text(encoding="utf-8"))
    meta = dict(raw_meta.get("audit_meta", raw_meta))  # unwrap nested wrapper
    meta["audit_date"] = meta.get("started_at", "")[:10]
    meta["catalog_version"] = f"v{meta.get('skill_version','?')} (hash {meta.get('catalog_hash','')[:12]})"
    results = {}
    raw_dir = OUT/"raw"; raw_dir.mkdir(exist_ok=True)
    find_dir = OUT/"findings"; find_dir.mkdir(exist_ok=True)
    for (cid,cat,sev,status,ev,gaps,obs,exp,rem,eff) in CHECKS:
        results[cid] = {"status":status,"category":cat,"severity":sev,
                        "evidence":ev,"gaps":gaps}
        # raw audit-trail
        rl = [f"# {cid} — verification ({status.upper()})","",
              "## Evidence"]+[f"- {e}" for e in ev]
        if gaps:
            rl += ["","## Gaps"]+[f"- {g}" for g in gaps]
        (raw_dir/f"{cid}.txt").write_text("\n".join(rl)+"\n",encoding="utf-8")
        # finding doc for fail/partial
        if status in ("fail","partial"):
            f = [f"## Finding: {cid}","",
                 f"**Severity:** {sev}",
                 f"**Status:** Open",
                 f"**Check:** {cid}  |  **Result:** {status}",
                 f"**Server:** swiss-democracy-mcp","",
                 "### Observed Behavior",obs or "(siehe Evidence)","",
                 "### Evidence"]+[f"- {e}" for e in ev]+[""]
            if gaps:
                f += ["### Gaps"]+[f"- {g}" for g in gaps]+[""]
            f += ["### Expected Behavior",exp or "(siehe Check-Definition)","",
                  "### Remediation",rem or "(siehe Check-Remediation)","",
                  "### Effort",eff or "—",""]
            (find_dir/f"{cid}-{slug(cid)}.md").write_text("\n".join(f)+"\n",encoding="utf-8")
    vr = {"audit_meta":meta,"results":results}
    (OUT/"verification-results.json").write_text(
        json.dumps(vr,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
    print(f"Wrote verification-results.json with {len(results)} checks")
    fails=[c for c in results if results[c]['status']=='fail']
    parts=[c for c in results if results[c]['status']=='partial']
    pas=[c for c in results if results[c]['status']=='pass']
    print(f"PASS={len(pas)} PARTIAL={len(parts)} FAIL={len(fails)}")
    print("FAIL:",fails)

if __name__=="__main__":
    main()
